



const fs = require("fs");

fs.readFile("books.json", "utf8", function (err, books) {
  books = JSON.parse(books);

  fs.writeFile("booksClean.json", JSON.stringify(books.map(book => {

    book.publisher_date = +book.publisher_date
    book.content = strip_html_tags(replaceSpecialCharacters(book.content))
    book.pages = +book.pages
    delete book.ID;
    delete book.content_short;
    delete book.publisher;
    delete book.language;
    delete book.url_details;
    delete book.url_download;
    delete book.thumbnail;
    delete book.num_comments;
    delete book.tags;
    delete book.categories[0].category_id;
    delete book.categories[0].nicename;
    delete book.categories.splice(1,2);
  

    return book
      
    
  })), function (err, data) {
    console.log("All good :)")
  })
})

function replaceSpecialCharacters(str) {
  return str.replace(/&quot;/g, `"`)
    .replace(/&amp;/g, `&`)
    .replace(/&ndash;/g, ` - `)
    .replace(/&frasl;/g, `/`)
    .replace(/&lt;/g, `<`)
    .replace(/&gt;/g, `>`)
    .replace(/&sbquo;/g, `‚`)
    .replace(/&bdquo;/g, `„`)
    .replace(/&dagger;/g, `†`)
    .replace(/&Dagger;/g, `‡`)
    .replace(/&permil;/g, `‰`)
    .replace(/&lsaquo;/g, `‹`)
    .replace(/&lsquo;/g, `‘`)
    .replace(/&rsquo;/g, `’`)
    .replace(/&ldquo;/g, `“`)
    .replace(/&rdquo;/g, `”`)
    .replace(/&trade;/g, `™`)
    .replace(/&rsaquo;/g, `›`)
    .replace(/&nbsp;/g, `Non`)
    .replace(/&iexcl;/g, `¡`)
    .replace(/&cent;/g, `¢`)
    .replace(/&pound;/g, `£`)
    .replace(/&curren;/g, `¤`)
    .replace(/&yen;/g, `¥`)
    .replace(/&brvbar;/g, `¦`)
    .replace(/&sect;/g, `§`)
    .replace(/&uml;/g, `¨`)
    .replace(/&copy;/g, `©`)
    .replace(/&ordf;/g, `ª`)
    .replace(/&laquo;/g, `«`)
    .replace(/&not;/g, `¬`)
    .replace(/&shy;/g, `­`)
    .replace(/&reg;/g, `®`)
    .replace(/&macr;/g, `¯`)
    .replace(/&deg;/g, `°`)
    .replace(/&plusmn;/g, `±`)
    .replace(/&sup2;/g, `²`)
    .replace(/&sup3;/g, `³`)
    .replace(/&acute;/g, `´`)
    .replace(/&micro;/g, `µ`)
    .replace(/&para;/g, `¶`)
    .replace(/&middot;/g, `·`)
    .replace(/&cedil;/g, `¸`)
    .replace(/&sup1;/g, `¹`)
    .replace(/&ordm;/g, `º`)
    .replace(/&raquo;/g, `»`)
    .replace(/&frac14;/g, `¼`)
    .replace(/&frac12;/g, `½`)
    .replace(/&frac34;/g, `¾`)
    .replace(/&iquest;/g, `¿`)
    .replace(/&Agrave;/g, `À`)
    .replace(/&Aacute;/g, `Á`)
    .replace(/&Acirc;/g, `Â`)
    .replace(/&Atilde;/g, `Ã`)
    .replace(/&Auml;/g, `Ä`)
    .replace(/&Aring;/g, `Å`)
    .replace(/&AElig;/g, `Æ`)
    .replace(/&Ccedil;/g, `Ç`)
    .replace(/&Egrave;/g, `È`)
    .replace(/&Eacute;/g, `É`)
    .replace(/&Ecirc;/g, `Ê`)
    .replace(/&Euml;/g, `Ë`)
    .replace(/&Igrave;/g, `Ì`)
    .replace(/&Iacute;/g, `Í`)
    .replace(/&Icirc;/g, `Î`)
    .replace(/&Iuml;/g, `Ï`)
    .replace(/&ETH;/g, `Ð`)
    .replace(/&Ntilde;/g, `Ñ`)
    .replace(/&Ograve;/g, `Ò`)
    .replace(/&Oacute;/g, `Ó`)
    .replace(/&Ocirc;/g, `Ô`)
    .replace(/&Otilde;/g, `Õ`)
    .replace(/&Ouml;/g, `Ö`)
    .replace(/&times;/g, `×`)
    .replace(/&Oslash;/g, `Ø`)
    .replace(/&Ugrave;/g, `Ù`)
    .replace(/&Uacute;/g, `Ú`)
    .replace(/&Ucirc;/g, `Û`)
    .replace(/&Uuml;/g, `Ü`)
    .replace(/&Yacute;/g, `Ý`)
    .replace(/&THORN;/g, `Þ`)
    .replace(/&szlig;/g, `ß`)
    .replace(/&agrave;/g, `à`)
    .replace(/&aacute;/g, `á`)
    .replace(/&acirc;/g, `â`)
    .replace(/&atilde;/g, `ã`)
    .replace(/&auml;/g, `ä`)
    .replace(/&aring;/g, `å`)
    .replace(/&aelig;/g, `æ`)
    .replace(/&ccedil;/g, `ç`)
    .replace(/&egrave;/g, `è`)
    .replace(/&eacute;/g, `é`)
    .replace(/&ecirc;/g, `ê`)
    .replace(/&euml;/g, `ë`)
    .replace(/&igrave;/g, `ì`)
    .replace(/&iacute;/g, `í`)
    .replace(/&icirc;/g, `î`)
    .replace(/&iuml;/g, `ï`)
    .replace(/&eth;/g, `ð`)
    .replace(/&ntilde;/g, `ñ`)
    .replace(/&ograve;/g, `ò`)
    .replace(/&oacute;/g, `ó`)
    .replace(/&ocirc;/g, `ô`)
    .replace(/&otilde;/g, `õ`)
    .replace(/&ouml;/g, `ö`)
    .replace(/&divide;/g, `÷`)
    .replace(/&oslash;/g, `ø`)
    .replace(/&ugrave;/g, `ù`)
    .replace(/&uacute;/g, `ú`)
    .replace(/&ucirc;/g, `û`)
    .replace(/&uuml;/g, `ü`)
    .replace(/&yacute;/g, `ý`)
    .replace(/&thorn;/g, `þ`)
    .replace(/&yuml;/g, `ÿ`)
    .replace(/&fnof;/g, `ƒ`)
    .replace(/&Alpha;/g, `Α`)
    .replace(/&Beta;/g, `Β`)
    .replace(/&Gamma;/g, `Γ`)
    .replace(/&Delta;/g, `Δ`)
    .replace(/&Epsilon;/g, `Ε`)
    .replace(/&Zeta;/g, `Ζ`)
    .replace(/&Eta;/g, `Η`)
    .replace(/&Theta;/g, `Θ`)
    .replace(/&Iota;/g, `Ι`)
    .replace(/&Kappa;/g, `Κ`)
    .replace(/&Lambda;/g, `Λ`)
    .replace(/&Mu;/g, `Μ`)
    .replace(/&Nu;/g, `Ν`)
    .replace(/&Xi;/g, `Ξ`)
    .replace(/&Omicron;/g, `Ο`)
    .replace(/&Pi;/g, `Π`)
    .replace(/&Rho;/g, `Ρ`)
    .replace(/&Sigma;/g, `Σ`)
    .replace(/&Tau;/g, `Τ`)
    .replace(/&Upsilon;/g, `Υ`)
    .replace(/&Phi;/g, `Φ`)
    .replace(/&Chi;/g, `Χ`)
    .replace(/&Psi;/g, `Ψ`)
    .replace(/&Omega;/g, `Ω`)
    .replace(/&alpha;/g, `α`)
    .replace(/&beta;/g, `β`)
    .replace(/&gamma;/g, `γ`)
    .replace(/&delta;/g, `δ`)
    .replace(/&epsilon;/g, `ε`)
    .replace(/&zeta;/g, `ζ`)
    .replace(/&eta;/g, `η`)
    .replace(/&theta;/g, `θ`)
    .replace(/&iota;/g, `ι`)
    .replace(/&kappa;/g, `κ`)
    .replace(/&lambda;/g, `λ`)
    .replace(/&mu;/g, `μ`)
    .replace(/&nu;/g, `ν`)
    .replace(/&xi;/g, `ξ`)
    .replace(/&omicron;/g, `ο`)
    .replace(/&pi;/g, `π`)
    .replace(/&rho;/g, `ρ`)
    .replace(/&sigmaf;/g, `ς`)
    .replace(/&sigma;/g, `σ`)
    .replace(/&tau;/g, `τ`)
    .replace(/&upsilon;/g, `υ`)
    .replace(/&phi;/g, `φ`)
    .replace(/&chi;/g, `χ`)
    .replace(/&psi;/g, `ψ`)
    .replace(/&omega;/g, `ω`)
    .replace(/&thetasym;/g, `ϑ`)
    .replace(/&upsih;/g, `ϒ`)
    .replace(/&piv;/g, `ϖ`)
    .replace(/&bull;/g, `•`)
    .replace(/&hellip;/g, `…`)
    .replace(/&prime;/g, `′`)
    .replace(/&Prime;/g, `″`)
    .replace(/&oline;/g, `‾`)
    .replace(/&image;/g, `ℑ`)
    .replace(/&weierp;/g, `℘`)
    .replace(/&real;/g, `ℜ`)
    .replace(/&alefsym;/g, `ℵ`)
    .replace(/&larr;/g, `←`)
    .replace(/&uarr;/g, `↑`)
    .replace(/&rarr;/g, `→`)
    .replace(/&darr;/g, `↓`)
    .replace(/&harr;/g, `↔`)
    .replace(/&crarr;/g, `↵`)
    .replace(/&lArr;/g, `⇐`)
    .replace(/&uArr;/g, `⇑`)
    .replace(/&rArr;/g, `⇒`)
    .replace(/&dArr;/g, `⇓`)
    .replace(/&hArr;/g, `⇔`)
    .replace(/&forall;/g, `∀`)
    .replace(/&part;/g, `∂`)
    .replace(/&exist;/g, `∃`)
    .replace(/&empty;/g, `∅`)
    .replace(/&nabla;/g, `∇`)
    .replace(/&isin;/g, `∈`)
    .replace(/&notin;/g, `∉`)
    .replace(/&ni;/g, `∋`)
    .replace(/&prod;/g, `∏`)
    .replace(/&sum;/g, `∑`)
    .replace(/&minus;/g, `−`)
    .replace(/&lowast;/g, `∗`)
    .replace(/&radic;/g, `√`)
    .replace(/&prop;/g, `∝`)
    .replace(/&infin;/g, `∞`)
    .replace(/&ang;/g, `∠`)
    .replace(/&and;/g, `∧`)
    .replace(/&or;/g, `∨`)
    .replace(/&cap;/g, `∩`)
    .replace(/&cup;/g, `∪`)
    .replace(/&int;/g, `∫`)
    .replace(/&there4;/g, `∴`)
    .replace(/&sim;/g, `∼`)
    .replace(/&cong;/g, `≅`)
    .replace(/&asymp;/g, `≈`)
    .replace(/&ne;/g, `≠`)
    .replace(/&equiv;/g, `≡`)
    .replace(/&le;/g, `≤`)
    .replace(/&ge;/g, `≥`)
    .replace(/&sub;/g, `⊂`)
    .replace(/&sup;/g, `⊃`)
    .replace(/&nsub;/g, `⊄`)
    .replace(/&sube;/g, `⊆`)
    .replace(/&supe;/g, `⊇`)
    .replace(/&oplus;/g, `⊕`)
    .replace(/&otimes;/g, `⊗`)
    .replace(/&perp;/g, `⊥`)
    .replace(/&sdot;/g, `⋅`)
    .replace(/&lceil;/g, `⌈`)
    .replace(/&rceil;/g, `⌉`)
    .replace(/&lfloor;/g, `⌊`)
    .replace(/&rfloor;/g, `⌋`)
    .replace(/&lang;/g, `〈`)
    .replace(/&rang;/g, `〉`)
    .replace(/&loz;/g, `◊`)
    .replace(/&spades;/g, `♠`)
    .replace(/&clubs;/g, `♣`)
    .replace(/&hearts;/g, `♥`)
    .replace(/&diams;/g, `♦`)
}

function strip_html_tags(str) {
  if ((str === null) || (str === ''))
    return false;
  else {
    str = str.toString();
    
    str = str.replace(/<\/li>/g, " ")
    str = str.replace(/<\/p>/g, " ")
    str = str.replace(/\s\s/g, " ")

    return str.replace(/<[^>]*>/g, ' ');
  }
}